# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# used to release in GITHUB
env_files:
  github_token: ~/.goreleaser/gh_token

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

    ldflags:
      - -s -w -X github.com/andresbott/yamlfmt/app/cli.Version={{.Version}}
      - -s -w -X github.com/andresbott/yamlfmt/app/cli.BuildTime={{.Date}}
      - -s -w -X github.com/andresbott/yamlfmt/app/cli.ShaVer={{.Commit}}

archives:
  - replacements:
      linux: Linux

# see full detail: https://goreleaser.com/customization/nfpm/
nfpms:
  -
    id: yamlfmt
    package_name: yamlfmt

    maintainer: "Andres Bott <contact@andresbott.com>"
    description: |
      format yaml files to a opinionated defaults, it is inspired ing go fmt.
    license: LGPL
    formats:
      - deb

    # Version Prerelease.
    # Default is extracted from `version` if it is semver compatible.
#    prerelease: snapshot

    #pacakge classification
    section: default
    priority: optional

    # Scripts to execute during the installation of the package.
    # Keys are the possible targets during the installation process
    # Values are the paths to the scripts which will be executed
    scripts:
#      preinstall: "scripts/preinstall.sh"
      postinstall: "zarf/postinstall.sh"
#      preremove: "scripts/preremove.sh"
#      postremove: "scripts/postremove.sh"


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
